sudo: false
language: node_js
# safelist
branches:
  only:
  - master
  - auth
services:
  - mongodb
node_js:
  - '10'
# cache:
#     directories:
#       - node_modules # 缓存不经常更改的内容
before_install: 
  - openssl aes-256-cbc -K $encrypted_b894101e0158_key -iv $encrypted_b894101e0158_iv -in ./config/secureConfig_prod.js.enc -out ./config/secureConfig_prod.js -d
  - openssl aes-256-cbc -K $encrypted_383bc2ea2d21_key -iv $encrypted_383bc2ea2d21_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
install:
  - npm install
before_script: 
  - sudo redis-server /etc/redis/redis.conf --requirepass  $redis_password
  - mkdir -p data/db
  - mongod --dbpath=data/db &
  - sleep 2
script:
  npm test
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR $deploy_user@39.107.119.46:$DEPLOY_PATH
  on:
    branch: master

after_deploy:
  - ssh $deploy_user@39.107.119.46 "pm2 restart www"
  - ssh $deploy_user@39.107.119.46 "sh $CLUSTER_SH_PATH/cluster.sh"
addons:
  ssh_known_hosts: 39.107.119.46 # 请替换成自己的服务器IP
#after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js -repotoken $COVERALLS_TOKEN   
